# Generated by Django 5.0.5 on 2024-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_labels_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='labels',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('documentation', 'Documentation'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], default='bug', max_length=20),
        ),
    ]
