# Generated by Django 5.0.5 on 2024-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
